on:
  workflow_dispatch:
    inputs:
      version:
        description: Web Version
        default: v1.0.0
        required: true
      
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run generate
            
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: wp10633224.server-he.de
        username: ftp10633224-khri8
        password: ${{ secrets.password }}
        local-dir: './dist/'
        server-dir: 'www/sonnhalde-waldkirch/'